  const articles = [
    {
      chapter: 1,
      title: 'Miniubåtar med larvband',
      ingress: 'nej vksjrng ejud cefb u riu fiuh fzjd sje fjd jxgh ruhgudfuh gdslcns fbödiv frgvd',
      text: "Loresm ipsum dodnsjd jsd jsdbshd sh dh shd shd shd hs dhsdg shd hs s dh sdhsd hds h dhs dh shd hd dh shd hs dhsd h dh hd hd dh hd hd hd dhfbdf hd hdfbd hd hfd fh df df djf hdjf jd lor sitlmdef rgnjn dkm ekdm d wkdm wkd fwkfne ne jed ebjf efhb bdhfb dhfb dhbf hd fhdb fhbd fjbd jfb djf dj fdjfjdf fgjnf gjnrjgnfen ejrngfjen jnf jnewkfjn cjkesnfkjngfkjnfjkdnjkfnsjefnjen j fje fj jv rjgnj skdnj dfldjfb sbf jsb ejkbf jafjnbe jsfslckjehf ökjdf skdjfn dkjfn flskjdfn dlsakjd asdkjan r ngjnr jgnrn ofkjeojf idjs fef ehrhe öföjresnjngröjng sjnf sejnf jsen fgnr fng rdvdjngnrjnsjfn e dedncegjn rgrjng j gvfn gjndf ejf ejng rjgnjg jnrjg njngr jngrjnj g amkdjfienfiedwiojowjdojoet, usjdns dblirugh lfdl qpwiorkj äoöehgj KEJFN SJFS EBFJEFB LSJDBF fehf lksjdf kjlsd asjldb ajlhsb asbdhs jdhfb sbdfjshbfjhsebf jehsbf chsbef jheb fjhs dfhjbs efhbew fhjb jns d sjn jsnd js djsndjsnd jsdjns djnsjnd sdjndjs sjnd sjnds jdns djsnd ssu ex paulo apeirian. In facer virtute mePri ex modo libris incorrupte.",
      image: '1',
      text2: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      text3: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      id: '1',
    },
    {
      chapter: 2,
      title: 'Title 2',
      ingress: 'nej vkjrng ejud cefb u riu fiuh fzjd sje fjd jxgh ruhgudfuh gdslcns fbödiv frgvd',
      text: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      image: '1',
      text2: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      text3: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      id: '2',
    },
    {
      chapter: 3,
      title: 'Title 3',
      ingress: 'nej vkjrn j djs dskd dk skd skd sdk sdks dskd skd skd skd sdk sdskd ksd k kkd sg ejud cefb u riu fiuh fzjd sje fjd jxgh ruhgudfuh gdslcns fbödiv frgvd',
      text: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      image: '1',
      text2: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      text3: "sljklsc skc dkcs djfd fjds ssssss slsmcl  jdss dksjd dksjd hd jd fdjf djf djgfd fjfdjd dj j skdjdj sjdjs skd sj jf jdhdjfh djhfjhdf jhd jfh djfh djhfj dhf jdhf jdhf jd fjd fjd jfh dj fjd fdj fjhdj fhd hf djfjd fh fdjhf jfeih aesdhf ökehjf vldjkfh skje csmc smdksdhncj dnfjkd nfjnfjenj fj e jdf  dhf jdfj ff ekmd snfs dndsjn djnf djfn jf dfjvjjdnf cjedfn jds fsjndfjbjcbfdjbg sjd cjdf dfjdnf nfj dfkjdgjfngj csjdbf sdjbg dsjgb djbf sdjfb sljdbf sjdhbf sdljbf sdljbfgjsdbfgsdbjbsdjlfbsdjf sdf djbfjdfbjs dfjbsd lgskjfnlrsjgnljsdbvlejsbfgjlrdgj  f dksjng rjkb vrgdjfn js xcjf gednv rlkjgn vrgsh rjhsg sss segsh jrvng dbv xjfb vrdjg rj gjrhg jnbg  ghkjvn gkj fje kj fk sökgjn rjgjrkg g gdkjrgn vrkjg kj fgjkrgn drjbger jkbvnr jgbjksnbfv lkjdgn ösdjkhv dfkjgn ödlfkjbg lsdjhfbg ldjbv gldjbf dljkfbs flsdjbfd sfljdsbf sldjfbsd fsdljfb sdbvd gbfdb dfhbs dhbf defbsfhfj dfj dshbf ddshfbd fjhsdbf dhbf sjdhbf sdjbhbfhdsfb sjdhfbdshbf sljdbh slfhjbs dfb dfbhsd lbfh sdlbhg lbdsbfha sldfjbsn vdnf",
      id: '3',
    },
];

export default articles;
